env:
  global:
  - ENCRYPTION_LABEL: c602e3be279e
  - COMMIT_AUTHOR_EMAIL: vahid@dobisel.com
language: python
python: 3.5
sudo: required
dist: trusty
os:
- linux
- osx
matrix:
  exclude:
  - python: 3.5
  include:
  - os: linux
    python: 2.7
  - os: linux
    python: 3.3
  - os: linux
    python: 3.4
  - os: linux
    python: 3.5
    env:
    - DEPLOY_DOC=yes
    - RUN_COVERAGE=yes
    - PYPI_SDIST=yes
  - os: linux
    python: nightly
  - os: osx
    language: objective-c
    python: 2.7
    env:
    - PY=2
    - PY_SUFFIX=
    - PYPI_WHEEL=yes
  - os: osx
    language: objective-c
    python: 3.5
    env:
    - PY=3
    - PY_SUFFIX=3
    - PYPI_WHEEL=yes
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" && "$PY" == "3" ]]; then brew install python$PY_SUFFIX;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python$PY_SUFFIX; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python$( python
  -c 'import sys; print("%d.%d" % sys.version_info[:2])' )-dev || true    ; fi
- pip install -U pip setuptools wheel
- pip install -r requirement.txt
install:
- pip install -ve .
script:
- if [[ "$RUN_COVERAGE" == "yes" ]]; then coverage run --source pymlconf $(which nosetests);
  else nosetests; fi
after_success:
- if [[ "$RUN_COVERAGE" == "yes" ]]; then coveralls ; fi
deploy:
  provider: pypi
  user: Vahid.Mardani
  password:
    secure: B36EgPpgSTEneklHrsDPk8DA0r556PoQrepW24hPkm+kBkq0tluQ8xyT/vaFlMe348+M+OuUFLY2bHHpfciLJfS4ZOSNP2FGflV6RUuPJZjwVgzB7m8+afZQjcss5sDAJxJaV5Y4BAxEfbAAnjrYPkGzjl3N8YTRjeghyZZIQOw=
  skip_cleanup: true
  overwrite: true
  distributions: bdist_wheel
  on:
    tags: true
    all_branches: true
    repo: pylover/pymlconf
    condition: "$TRAVIS_TAG =~ ^v[0-9][.][0-9]*[.][0-9]*$"
after_deploy:
- if [[ "$PYPI_SDIST" == "yes" ]]; then python3 setup.py sdist upload; fi
- if [[ "$DEPLOY_DOC" == "yes" ]]; then ./travis-gh-pages.sh ; fi
